{"name": "Логин с неверным логином и паролем", "status": "passed", "start": 1730015527619, "stop": 1730015528165, "uuid": "ccad9cc2-21ad-4f3f-83e6-39f5e1142188", "historyId": "5997bdef8a74ace48d6cfb29a79d2f11", "testCaseId": "5997bdef8a74ace48d6cfb29a79d2f11", "fullName": "tests.test_user_login.TestUserLogin#test_wrong_login_and_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "MSI"}, {"name": "thread", "value": "8768-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}