{"name": "Логин с неверным логином и паролем", "status": "passed", "start": 1730039308627, "stop": 1730039309460, "uuid": "f6079e66-96bf-4f60-997c-a0aac5eada30", "historyId": "5997bdef8a74ace48d6cfb29a79d2f11", "testCaseId": "5997bdef8a74ace48d6cfb29a79d2f11", "fullName": "tests.test_user_login.TestUserLogin#test_wrong_login_and_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "MSI"}, {"name": "thread", "value": "15028-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}