{"name": "Логин с неверным логином и паролем", "status": "passed", "start": 1730015622372, "stop": 1730015622999, "uuid": "2d5cc8de-0525-4dd5-8d25-56d3b47e4e07", "historyId": "5997bdef8a74ace48d6cfb29a79d2f11", "testCaseId": "5997bdef8a74ace48d6cfb29a79d2f11", "fullName": "tests.test_user_login.TestUserLogin#test_wrong_login_and_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "MSI"}, {"name": "thread", "value": "668-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}